export const CSSROOTVARIABLES = {
  '--colour--bsi-red': '#ff2b1f',
  '--colour--black': '#000',
  '--colour--white': '#fff',
  '--colour--bsi-darker-red': '#d72d18',
  '--colour--bsi-pale-red': '#ffb9af',
  '--colour--bsi-light-red': '#ff8273',
  '--colour--bsi-dark-red': '#9e2b1f',
  '--colour--10-percent-black': '#ececec',
  '--colour--30-percent-black': '#c5c5c5',
  '--colour--50-percent-black': '#9b9b9b',
  '--colour--bsi-pale-teal': '#e6f6f7',
  '--colour--bsi-light-teal': '#b3e3e6',
  '--colour--bsi-teal': '#00a3ad',
  '--colour--bsi-teal--a11y': '#29828c',
  '--colour--platinum': '#ebebeb',
  '--colour--cultured': '#f2f2f2',  
  // '--font-family--primary' : 'Gesta, Tahoma, sans-serif',
  // '--font-size--small': '12px',
  // '--font-size--regular': '16px',
  // '--font-size--large': '21px',
  '--font-size--small': '10px',
  '--font-size--regular': '12px',
  '--font-size--large': '16px',
  '--font-weight--light': '300',
  '--font-weight--regular': '400',
  '--font-weight--medium': '500',
  '--transition-time': '0.22s',
  '--plain-node-color' : 'lavender'
};
