name: release

on:
  workflow_call:
  push:
    tags:
      - '*'
  workflow_dispatch:
    inputs:
      next_version:
        description: |
          Next release version. Possible values: x.y.z, major, minor, patch
        required: true
        default: 'skip'
      # XXX: does not skip for some reason
      # skip_tests:
      #   description: |
      #     Skip tests iff === 'true'
      #   required: true
      #   default: 'false'

env:
  CACHE_DIR: installs

jobs:
  tests:
    # XXX: does not skip for some reason
    # if: github.events.inputs.skip_tests != 'true'
    uses: ./.github/workflows/tests.yml

  publish:
    needs: [tests]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ['16.x']
      fail-fast: false

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - uses: actions/setup-node@v3
        id: setup-node
        with:
          node-version: ${{ matrix.node }}
          registry-url: 'https://registry.npmjs.org'

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        id: pnpm-install
        with:
          version: 7
          run_install: false

      # See: https:
        # //github.com/pnpm/action-setup#use-cache-to-reduce-installation-time
      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/.npmrc', '**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install --frozen-lockfile --strict-peer-dependencies

      # For rsync support in Windows
      - uses: GuillaumeFalourd/setup-rsync@v1.1
        if: matrix.os == 'windows-latest'

      - name: Restore cache
        id: build_cache
        uses: actions/cache@v3
        with:
          path: ${{ env.CACHE_DIR }}
          key: build-${{ runner.os }}-${{ matrix.node }}-${{ hashFiles('src/**', '**/.npmrc', 'tsconfig*.json', '**/pnpm-lock.yaml', '.github/workflows/build.yml') }}

      - name: Restore cache to working directory
        shell: bash
        run: |
          echo ls -la ${{ env.CACHE_DIR }}/
          ls -la ${{ env.CACHE_DIR }}/
          echo ls -la ${{ env.CACHE_DIR }}/*
          ls -la ${{ env.CACHE_DIR }}/*
          echo ls -la .
          ls -la .
          for i in dist; do \
            echo rsync -a ${{ env.CACHE_DIR }}/"$i"/ "$i"; \
            rsync -a ${{ env.CACHE_DIR }}/"$i"/ "$i"; \
          done
          echo ls -la .
          ls -la .
          echo ls -la dist/
          ls -la dist/
          echo ls -la dist/*
          ls -la dist/*

      - name: Create a new version
        if: github.event_name == 'workflow_dispatch' && github.event.inputs.next_version != 'skip'
        shell: bash
        run: |
          pnpm version --new-version ${{ github.event.inputs.next_version }}
          git push

      - name: Publish to npm
        run: |
          pnpm publish dist --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.PANERON_CI_NPM_TOKEN }}
